### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by deliciousmonster**

### CODE REVIEW

**Comment by yaodema** [comment]
What I'm seeing here looks good, though there is one edge case bug it introduces while fixing some "== should be =" in code we may need for the future.

in main/jsonptr.js, on line 22, it changes this:
```
-	if(ind == null) {
+	if(!ind) {
```

Doing this matches 0, which could be a request for the first element in an array without using the array format. This is why I checked `== null` instead of 0, so I could trap null and undefined.

How do we rearrange this so SolarCloud is happy? Should we move that `!ind` check down to below the check for type "number"? I normally prefer to do null checks before type checks, but I can tell the system won't like that here.

**Comment by deliciousmonster** [comment]
@yaodema can we check for `ind !== 0 && !ind`?

**Comment by deliciousmonster** [comment]
Let's see what sonarcloud has to say about that.

**Comment by deliciousmonster** [comment]
magic!

**Pull request merged**
